// Sample only — copy into your Unity project and adjust as needed.
// Not generated by xls2cfg. Referenced by Excel/__externtype__.json constructors.
using UnityEngine;

namespace Cfg {
    public static class ExternTypeUtil {
        public static Vector3 FromVec3(Vec3 v) {
            if (v == null) {
                return Vector3.zero;
            }
            return new Vector3(v.X, v.Y, v.Z);
        }

        public static Vec3 ToVec3(Vector3 v) {
            return new Vec3 { X = v.x, Y = v.y, Z = v.z };
        }
    }
}
